# fly.toml for multi-service configuration (API + Dashboard)
# Replace your existing fly.toml with this file when ready to deploy both services

app = 'happyrobot-inbound'
primary_region = 'ord'

[experimental]
  auto_rollback = true

[build]

[env]
  PORT = '8000'

[[services]]
  protocol = 'tcp'
  internal_port = 8000
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  # HTTP health checks with longer timeouts
  [[services.http_checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '60s'
    method = 'GET'
    path = '/health'

[[services]]
  protocol = 'tcp'
  internal_port = 8501
  processes = ['app']

  [[services.ports]]
    port = 8501
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 8502
    handlers = ['tls', 'http']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1