# fly.toml app configuration file generated for happyrobot-inbound on 2025-09-15T13:36:06-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'happyrobot-inbound'
primary_region = 'ord'

[experimental]
  auto_rollback = true

[build]

[env]
  PORT = '8000'

[[services]]
  protocol = 'tcp'
  internal_port = 8000

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  # HTTP health checks with longer timeouts
  [[services.http_checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '60s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
